# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
style = "blue bold"

[nodejs]
format = "[w/ node](bold italic fg:purple) [& $version](bold green) "


[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸  Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸  Ã—${count} "
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸  Ã—${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[directory]
#truncation_length = 5
format = "[â†’]($style) [$path]($style)[$lock_symbol]($lock_style) "
style = "bold italic blue"

[gcloud]
disabled = true

[aws]
style = "bold #ffb86c"

[character]
error_symbol =   "[â†’ âœ¨](bold #FF0000)"
success_symbol = "[â†’ âœ¨](bold #f8f8f2)"

[cmd_duration]
style = "bold #c634c9"
# time taken to complete a command

#[directory]
#style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

#[git_status]
#style = "bold #ff5555"

[vlang]
format = "[via](purple bold) [$symbol](blue bold)  [$version](purple bold) "
symbol = "ğŸ‡»"

[hostname]
style = "bold #ff5555"

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"
